version: '3.9'

services:
  app:
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: mongo:5
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB: OnLine-db
